// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgnpxiiluqsmcoitlsbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnbnB4aWlsdXFzbWNvaXRsc2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzkzNjYsImV4cCI6MjA2MTg1NTM2Nn0.jcrj3QAryJapVadgk2rGNV5AA8o0YJ51BCA8oLDg2Yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);